apiVersion: v1
kind: ReplicationController
metadata:
  name: prediction-cache
  labels:
    app: prediction-cache
    hystrix.enabled: "true"
spec:
  replicas: 1
  selector:
    name: prediction-cache
  template:
    metadata:
      labels:
        name: prediction-cache
        hystrix.enabled: "true"
    spec:
      containers:
      - name: prediction-cache
        image: docker.io/fluxcapacitor/prediction-cache
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: GITHUB_USER
          value: "cfregly"
        - name: GITHUB_EMAIL
          value: "chris@fregly.com"
        - name: GITHUB_REPO_OWNER_URL 
          value: "https://github.com/fluxcapacitor"
        - name: GITHUB_REPO_NAME 
          value: "source.ml"
        - name: GITHUB_CLONE_BRANCH
          value: "master"
        - name: GITHUB_CHECKOUT_BRANCH
          value: "master"
        - name: GITHUB_RESET_REVISION
          value: "HEAD"
        ports:
        - containerPort: 9040
#        livenessProbe:
#          httpGet:
#            path: "/health"
#            port: 9040
#          initialDelaySeconds: 300 
#        readinessProbe:
#          httpGet:
#            path: "/health"
#            port: 9040
#          initialDelaySeconds: 30 
