---
spring:
  profiles: local
eureka:
  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
  client:
    registerWithEureka: false
#    fetchRegistry: true
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#---
#spring:
#  profiles: cluster
#eureka:
#  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    healthcheck:
#      enabled: true
#    serviceUrl:
#      defaultZone: http://netflix:8761/eureka/
